server:
  port: 8002
#mybatis配置
mybatis:
  type-aliases-package: com.lmy.Springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#Spring配置
spring:
  application:
    name: Springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-8002 #修改eureka上的默认描述信息

#info配置
info:
  application:
    app.name: This is lmy APPLICATION
    version: v.1.0.1
    company.name: blog.lmy.com
#启动所有监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true







