server:
  port: 9527

#Spring配置
spring:
  application:
    name: Springcloud-zuul

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul9527.com #修改eureka上的默认描述信息
    prefer-ip-address: true

#info配置
info:
  application:
    app.name: This is lmy APPLICATION
    version: v.1.0.1
    company.name: blog.lmy.com
#启动所有监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

# zull 路由网关配置
zuul:
  # 路由相关配置
  routes:
    mydept.serviceId: springcloud-provider-dept # eureka注册中心的服务提供方路由名称
    mydept.path: /mydept/** # 将eureka注册中心的服务提供方路由名称 改为自定义路由名称
  # 不能再使用这个路径访问了，*： 忽略,隐藏全部的服务名称~
  ignored-services: "*"
  # 设置公共的前缀
  prefix: /lmy







